name: Build and Push Docker Image to Docker Hub and Deploy to Azure Web App
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fig:${{ github.ref_name }} .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fig:${{ github.ref_name }}

    # Step 6: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    # Step 7: Deploy Docker image to Azure Web App
    - name: Deploy to Azure Web App
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RG }} \
          --docker-custom-image-name ${{ secrets.DOCKER_HUB_USERNAME }}/fig:${{ github.ref_name }} \
          --docker-registry-server-url https://index.docker.io/v1/ \
          --docker-registry-server-user ${{ secrets.DOCKER_HUB_USERNAME }} \
          --docker-registry-server-password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}